export const SHOW_ADD_TO_CART_MODAL = 'SHOW_ADD_TO_CART_MODAL';
export const SHOW_REMOVE_FROM_CART_MODAL = 'SHOW_REMOVE_FROM_CART_MODAL';
export const SHOW_CHECKOUT_MODAL = 'SHOW_CHECKOUT_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';